apiVersion: 1

datasources:
  - name: Mise PostgreSQL
    type: grafana-postgresql-datasource
    url: postgres:5432
    database: mise
    user: mise
    secureJsonData:
      password: mise
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    uid: mise-postgres
    isDefault: true
    editable: false
