apiVersion: 1

datasources:
  - name: Mise PostgreSQL
    type: grafana-postgresql-datasource
    url: $GF_DS_URL
    database: $GF_DS_DATABASE
    user: $GF_DS_USER
    secureJsonData:
      password: $GF_DS_SECRET
    jsonData:
      sslmode: $GF_DS_SSLMODE
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    uid: mise-postgres
    isDefault: true
    editable: false
